version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_k8s
      POSTGRES_USER: test_k8s
      POSTGRES_PASSWORD: OwOtBep9Frut
    ports:
      - 192.168.8.100:5432:5432
volumes:
  db_data: