apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  namespace: edu-stoic-dubinsky
spec:
  schedule: "0 0 * * 1"
  startingDeadlineSeconds: 400
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 1800
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: morozdocker/django_app_k8_test:Rv6
            imagePullPolicy: IfNotPresent
            command: ["python", "manage.py", "clearsessions"]
            envFrom:
              - configMapRef:
                  name: configmap
              - secretRef:
                  name: django-secrets
          restartPolicy: OnFailure