apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  ttlSecondsAfterFinished: 720
  template:
    spec:
      containers:
      - name: django-migrate
        image: morozdocker/django_app_k8_test:Rv1
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py",  "migrate", "--no-input"]
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: SECRET_KEY
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: POSTGRES_DB
          - name: DEBUG
            value: "True"
          - name: ALLOWED_HOSTS
            value: '*'
      restartPolicy: Never